import 'package:get/get_navigation/get_navigation.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US':{
      'Login In': 'Login In',
      'Email': 'Email',
      'Please enter your email': 'Please enter your email',
      'Enter a valid email': 'Enter a valid email',
      'Password': 'Password',
      'Please enter your password': 'Please enter your password',
      'Password must be at least 6 characters':
          'Password must be at least 6 characters',
          'Forgot Password?': 'Forgot Password?',
          'Confirm Password':'Confirm Password',
          'Passwords do not match':'Passwords do not match',
      'Please enter your confirm password':'Please enter your confirm password',
      'LOGIN IN': 'LOGIN IN',
      'Continue with Phone ': 'Continue with Phone ',
       'Do\'nt have an account? ': 'Do\'nt have an account? ',
       'Register': 'Register',
       'Sign Up': 'Sign Up',
       'SIGN UP': 'SIGN UP',
      'Continue with Phone': 'Continue with Phone',
      'Continue with Gmail': 'Continue with Gmail',
      'Now':'Now',
      'Magrab': 'Magrab',
      'Upcoming': 'Upcoming',
      'Asha': 'Asha',
      '4:44 Pm': '4:44 Pm',
      'Sura Al Baqra': 'Sura Al Baqra','QS:Surah Al Baqra: Ayat 30': 'QS:Surah Al Baqra: Ayat 30',
      'Videos': 'Videos',
      'Quran':'Quran',
      'Duain':'Duain',
      'Names': 'Names',
      'Tasbeeh': 'Tasbeeh',
      'Quarnin Duain': 'Quarnin Duain',
      'Qibla': 'Qibla',
      'Dua Before Eating':'Dua Before Eating',
      'In the name of Allah and with the blessings of Allah.':
          'In the name of Allah and with the blessings of Allah.',
          'Abu Dawood 3767, Ahmad': 'Abu Dawood 3767, Ahmad',
          'Dua After Eating': 'Dua After Eating',
      'All praise is for Allah who fed me this and provided it for me without any might nor power from myself.':
      'All praise is for Allah who fed me this and provided it for me without any might nor power from myself.',
      'Abu Dawood 4023, Tirmidhi 3458': 'Abu Dawood 4023, Tirmidhi 3458',
      'Dua Before Sleeping': 'Dua Before Sleeping',
      'In Your name, O Allah, I die and I live.':
          'In Your name, O Allah, I die and I live.',
          'Bukhari 6324': 'Bukhari 6324',
          'Dua After Waking Up': 'Dua After Waking Up',
          'Praise is to Allah Who gave us life after He caused us to die, and to Him is the return.':
          'Praise is to Allah Who gave us life after He caused us to die, and to Him is the return.',
          'Bukhari 6312, Muslim 2711': 'Bukhari 6312, Muslim 2711',
          'Dua When Entering the Toilet': 'Dua When Entering the Toilet',
          'O Allah, I seek refuge with You from all evil and evil-doers.':
          'O Allah, I seek refuge with You from all evil and evil-doers.',
          'Bukhari 142, Muslim 375': 'Bukhari 142, Muslim 375',
          'Dua After Leaving the Toilet': 'Dua After Leaving the Toilet',
          'I ask You for Your forgiveness.': 'I ask You for Your forgiveness.',
          'Abu Dawood 30, Ibn Majah 300': 'Abu Dawood 30, Ibn Majah 300',
          'Dua When Leaving the House': 'Dua When Leaving the House',
           'In the name of Allah, I place my trust in Allah, and there is no might nor power except with Allah.':
          'In the name of Allah, I place my trust in Allah, and there is no might nor power except with Allah.',
          'Abu Dawood 5095, Tirmidhi 3426': 'Abu Dawood 5095, Tirmidhi 3426',
          'Dua When Entering the House': 'Dua When Entering the House',
          'O Allah, I ask You for the best of entrances and the best of exits.':
          'O Allah, I ask You for the best of entrances and the best of exits.',
          'Abu Dawood 5096': 'Abu Dawood 5096',
          'Dua for Traveling': 'Dua for Traveling',
          'Glory is to Him Who has made this [vehicle] subservient to us, and we ourselves could never have accomplished it. And verily, to our Lord we are returning.':
          'Glory is to Him Who has made this [vehicle] subservient to us, and we ourselves could never have accomplished it. And verily, to our Lord we are returning.',
          'Dua When in Distress': 'Dua When in Distress',
          'There is none worthy of worship except Allah, the Most Great, the Most Forbearing. There is none worthy of worship except Allah, the Lord of the Mighty Throne.':
          'There is none worthy of worship except Allah, the Most Great, the Most Forbearing. There is none worthy of worship except Allah, the Lord of the Mighty Throne.',
          'Bukhari 6345, Muslim 2730': 'Bukhari 6345, Muslim 2730',
          'Translation: ': 'Translation: ',
          'Reference: ': 'Reference: ',
          'Asma Ul Husna': 'Asma Ul Husna',
          'Names of Allah': 'Names of Allah',
          'Ar-Rahmān': 'Ar-Rahmān',
          'Ar-Rahīm': 'Ar-Rahīm',
          'The Bestower of Mercy':'The Bestower of Mercy',
          'Al-Malik': 'Al-Malik',
          'The King and Owner of Dominion': 'The King and Owner of Dominion',
          'Al-Quddūs': 'Al-Quddūs',
          'The Absolutely Pure': 'The Absolutely Pure',
          'As-Salām': 'As-Salām',
          'The Source of Peace, Safety, and Perfection':
          'The Source of Peace, Safety, and Perfection',
          'Al-Mu’min': 'Al-Mu’min',
          'The One Who gives Emaan and Security':
          'The One Who gives Emaan and Security',
          'Al-Muhaymin': 'Al-Muhaymin',
          'The Guardian, The Witness, The Overseer':
          'The Guardian, The Witness, The Overseer',
          'Al-‘Azīz': 'Al-‘Azīz',
          'The Almighty':'The Almighty',
          'Al-Jabbār': 'Al-Jabbār',
          'The Compeller, The Restorer':'The Compeller, The Restorer',
          'Al-Mutakabbir': 'Al-Mutakabbir',
          'The Supreme, The Majestic': 'The Supreme, The Majestic',
          'Al-Khāliq': 'Al-Khāliq',
          'The Creator, The Maker': 'The Creator, The Maker',
          'Al-Bāriʾ' :'Al-Bāriʾ',
          'Al-Muṣawwir': 'Al-Muṣawwir',
          'The Fashioner': 'The Fashioner',
          'Al-Ghaffār': 'Al-Ghaffār',
          'The Constant Forgiver': 'The Constant Forgiver',
          'Al-Qahhār': 'Al-Qahhār',
          'The All-Subduer': 'The All-Subduer',
          'Al-Wahhāb': 'Al-Wahhāb',
          'The Supreme Bestower': 'The Supreme Bestower',
          'Ar-Razzāq':'Ar-Razzāq',
          'The Provider': 'The Provider',
          'Al-Fattāḥ': 'Al-Fattāḥ',
          'The Supreme Opener':'The Supreme Opener',
          'Al-‘Alīm':'Al-‘Alīm',
          'The All-Knowing': 'The All-Knowing',   
          'Al-Qābiḍ': 'Al-Qābiḍ',
          'The Withholder': 'The Withholder',
          'Al-Bāsiṭ': 'Al-Bāsiṭ',
          'The Extender': 'The Extender',
          'Al-Khāfiḍ': 'Al-Khāfiḍ',
          'The Reducer': 'The Reducer',
          'Ar-Rāfiʿ': 'Ar-Rāfiʿ',
          'The Exalter, The Elevator': 'The Exalter, The Elevator',
          'Al-Muʿizz': 'Al-Muʿizz',
          'The Honourer, the Bestower': 'The Honourer, the Bestower',
          'Al-Mudhill': 'Al-Mudhill',
          'The Dishonourer': 'The Dishonourer',
          'As-Samīʿ': 'As-Samīʿ',
          'The All-Hearing':'The All-Hearing',
          'Al-Baṣīr': 'Al-Baṣīr',
          'The All-Seeing': 'The All-Seeing',
          'Al-Ḥakam': 'Al-Ḥakam',
          'The Impartial Judge': 'The Impartial Judge',
          'Al-ʿAdl': 'Al-ʿAdl',
          'The Utterly Just':'The Utterly Just',
          'Al-Laṭīf': 'Al-Laṭīf',
          'The Subtle One, The Most Gentle':'The Subtle One, The Most Gentle',
          'Al-Khabīr': 'Al-Khabīr',
          'The Acquainted, The All-Aware': 'The Acquainted, The All-Aware',
          'Al-Ḥalīm':'Al-Ḥalīm',
          'The Most Forbearing':'The Most Forbearing',
          'Al-ʿAẓīm': 'Al-ʿAẓīm',
          'The Magnificent, The Supreme': 'The Magnificent, The Supreme',
          'Al-Ghafūr':'Al-Ghafūr',
          'The Forgiving, The Exceedingly Forgiving':
          'The Forgiving, The Exceedingly Forgiving',
          'Ash-Shakūr': 'Ash-Shakūr',
          'The Most Appreciative':'The Most Appreciative',
          'Al-ʿAlī':'Al-ʿAlī',
          'The Most High, The Exalted':'The Most High, The Exalted',
          'Al-Kabīr':'Al-Kabīr',
          'The Greatest, The Most Grand': 'The Greatest, The Most Grand',
          'Al-Ḥafīẓ':'Al-Ḥafīẓ',
          'The Preserver, The All-Heedful and All-Protecting':'The Preserver, The All-Heedful and All-Protecting',
          'Al-Muqīt':'Al-Muqīt',
          'The Sustainer, The Maintainer':'The Sustainer, The Maintainer',
          'Al-Ḥasīb': 'Al-Ḥasīb',
          'The Reckoner':'The Reckoner',
          'Al-Jalīl':'Al-Jalīl',
          'The Majestic':'The Majestic',
          'Al-Karīm':'Al-Karīm',
          'The Most Generous, The Most Esteemed':
          'The Most Generous, The Most Esteemed',
          'Ar-Raqeeb':'Ar-Raqeeb',
          'The Watchful, The All-Watchful':'The Watchful, The All-Watchful',
          'Al-Mujeeb':'Al-Mujeeb',
          'The Responsive, The Answerer': 'The Responsive, The Answerer',
          'Al-Waasi’': 'Al-Waasi’',
          'The All-Encompassing, the Boundless':'The All-Encompassing, the Boundless',
          'Al-Hakeem': 'Al-Hakeem',
          'The All-Wise': 'The All-Wise',
          'Al-Wadud': 'Al-Wadud',
          'The Most Loving': 'The Most Loving',
          'Al-Majeed':'Al-Majeed',
          'The Glorious, The Most Honorable':'The Glorious, The Most Honorable',
          'Al-Baa’ith':'Al-Baa’ith',
          'The Infuser of New Life':'The Infuser of New Life',
          'As-Shaheed':'As-Shaheed',
          'The All Observing Witnessing':'The All Observing Witnessing',
          'Al-Haqq':'Al-Haqq',
          'The Absolute Truth': 'The Absolute Truth',
          'Al-Wakeel': 'Al-Wakeel',
          'The Trustee, The Disposer of Affairs':
          'The Trustee, The Disposer of Affairs',
          'Al-Qawiyy':'Al-Qawiyy',
          'The All-Strong': 'The All-Strong',
          'Al-Mateen':'Al-Mateen',
          'The Firm, The Steadfast': 'The Firm, The Steadfast',
          'Al-Walee':'Al-Walee',
          'The Protecting Associate':'The Protecting Associate',
          'Al-Hameed':'Al-Hameed',
          'The Praiseworthy':'The Praiseworthy',
          'Al-Muhsee': 'Al-Muhsee',
          'The All-Enumerating, The Counter':'The All-Enumerating, The Counter',
          'Al-Mubdi’':'Al-Mubdi’',
          'The Originator, The Initiator':'The Originator, The Initiator',
          'Al-Mu’id':'Al-Mu’id',
          'The Restorer, The Reinstater':'The Restorer, The Reinstater',
          'Al-Muhyee': 'Al-Muhyee',
          '	The Giver of Life': '	The Giver of Life',
          'Al-Mumeet': 'Al-Mumeet',
          'The Creator of Death':'The Creator of Death',
          'Al-Hayy': 'Al-Hayy',
          'The Ever-Living':'The Ever-Living',
          'Al-Qayyoom':'Al-Qayyoom',
          'The Sustainer, The Self-Subsisting':
          'The Sustainer, The Self-Subsisting',
          'Al-Waajid':'Al-Waajid',
          'The Perceiver':'The Perceiver',
          'Al-Maajid':'Al-Maajid',
          'The Illustrious, The Magnificent': 'The Illustrious, The Magnificent',//
          'Al-Waahid':'Al-Waahid',
      'The One, The Indivisible': 'The One, The Indivisible',
      'Al-Ahad':'Al-Ahad',
      'The Unique, The Only One': 'The Unique, The Only One',
      'As-Samad':'As-Samad',
      'The Eternal, Satisfier of Needs': 'The Eternal, Satisfier of Needs',
      'Al-Qaadir':'Al-Qaadir',
      'The Omnipotent':'The Omnipotent',
      'Al-Muqtadir':'Al-Muqtadir',
      'The Powerful':'The Powerful',
      'Al-Muqaddim':'Al-Muqaddim',
      'The Expediter, The Promoter':'The Expediter, The Promoter',
      'Al-Mu’akhkhir':'Al-Mu’akhkhir',
      '	The Delayer': '	The Delayer',
      'Al-Awwal':'Al-Awwal',
      'The First':'The First',
      'Al-Aakhir':'Al-Aakhir',
      'The Last, The Utmost':'The Last, The Utmost',
      'Az-Zaahir': 'Az-Zaahir',
      'The Manifest, The All-Surpassing': 'The Manifest, The All-Surpassing',
      'Al-Baatin':'Al-Baatin',
      'The Hidden One, Knower of the Hidden':'The Hidden One, Knower of the Hidden',
      'Al-Waalee	': 'Al-Waalee	',
      'he Sole Governor': 'he Sole Governor',
      'Al-Muta’ali':'Al-Muta’ali',
      'The Self Exalted':'The Self Exalted',
      'Al-Barr':'Al-Barr',
      'The Source of All Goodness':'The Source of All Goodness',
      'At-Tawwaab':'At-Tawwaab',
      'The Ever-Pardoning':'The Ever-Pardoning',
      'Al-Muntaqim':'Al-Muntaqim',
      'The Avenger':'The Avenger',
      'Al-‘Afuww':'Al-‘Afuww',
      'The Pardoner':'The Pardoner',
      'Ar-Ra’ūf': 'Ar-Ra’ūf',
      'The Most Kind':'The Most Kind',
      'Mālik al-Mulk':'Mālik al-Mulk',
      'Master of the Dominion,\nOwner of the Kingdom':'Master of the Dominion,\nOwner of the Kingdom',
      'Thul-Jalaali wal-Ikraam':'Thul-Jalaali wal-Ikraam',
      'Possessor of Glory and Honour': 'Possessor of Glory and Honour',
      'Al-Muqsiṭ': 'Al-Muqsiṭ',
      'The Just One':'The Just One',
      'Al-Jaami’': 'Al-Jaami’',
      'The Gatherer, the Uniter':'The Gatherer, the Uniter',
      'Al-Ghaniyy':'Al-Ghaniyy',
      'The Self-Sufficient, The Wealthy':'The Self-Sufficient, The Wealthy',
      'Al-Mughniyy':'Al-Mughniyy',
      'The Enricher':'The Enricher',
      'Al-Maani’': 'Al-Maani’',
      'The With holder': 'The With holder',
      'Ad-Dārr': 'Ad-Dārr',
      'The Distresser':'The Distresser',
      'An-Naafi’': 'An-Naafi’',
      'The Propitious, The Benefactor':'The Propitious, The Benefactor',
      'An-Noor': 'An-Noor',
      'The Light': 'The Light',
      'Al-Haadi': 'Al-Haadi',
      'The Guide': 'The Guide',
      'Al-Badee’':'Al-Badee’',
      'The Incomparable Originator':'The Incomparable Originator',
      'Al-Baaqi':'Al-Baaqi',
      'The Ever-Lasting':'The Ever-Lasting',
      'Al-Waarith':'Al-Waarith',
      'The Inheritor': 'The Inheritor',
      'Ar-Rasheed':'Ar-Rasheed',
      'The Guide to the Right Path': 'The Guide to the Right Path',
      'Al-Saboor':'Al-Saboor',
      'The Patient':'The Patient',
      'Alif Laam Meem': 'Alif Laam Meem',
      'Sayaqool':'Sayaqool',
      'Tilkal Rusul':'Tilkal Rusul',
      'Lan Tanaalu': 'Lan Tanaalu',
      'Wal Mohsanaat': 'Wal Mohsanaat',
      'La Yuhibbullah': 'La Yuhibbullah',
      'Wa Iza Samiu': 'Wa Iza Samiu',
      'Wa Lau Annana':'Wa Lau Annana',
      'Qad Aflaha':'Qad Aflaha',
      'Wa A’lamu':'Wa A’lamu',
      'Ya’tazerun':'Ya’tazerun',
      'Wama Min Daabbah':'Wama Min Daabbah',
      'Wama Ubarri-u': 'Wama Ubarri-u',
      'Rubama':'Rubama',
      'Subhanallazi':'Subhanallazi',
      'Qaal Alam': 'Qaal Alam',
      'Aqtarabat':'Aqtarabat',
      'Qadd Aflaha':'Qadd Aflaha',
      'Wa Qalallazina': 'Wa Qalallazina',
      'A’man Khalaq': 'A’man Khalaq',
      'Utlu Ma Uhiya':'Utlu Ma Uhiya',
      'Wa Man Yaqnut':'Wa Man Yaqnut',
      'Wama Liya': 'Wama Liya',
      'Faman Azlam':'Faman Azlam',
      'Ilayhi Yuraddu':'Ilayhi Yuraddu',
      'Ha Meem':'Ha Meem',
      'Qad Sami Allah':'Qad Sami Allah',
      'Tabaarak': 'Tabaarak',
      'Amma Yatasa’alun':'Amma Yatasa’alun',
      'Amma':'Amma',
      'Juzz':'Juzz',
      'Setting':'Setting',
      'Account':'Account',
      'Privacy, security, change number':'Privacy, security, change number',
      'Notifications':'Notifications',
      'Message, group & call tones':'Message, group & call tones',
      'Language': 'Language',
      'App language':'App language',
      'Theme': 'Theme',
          'Light / Dark mode':'Light / Dark mode',
      'About':'About',
      'App version, developer info':'App version, developer info',
      'Logout':'Logout',
      'Qaris List':'Qaris List',
      'Surah List':'Surah List', "Translation": "Translation",
      "Tafseer": "Tafseer",
      
    },
    'ur_PK': {
      'Login In': 'لاگ ان کریں',
      'Email': 'ای میل',
      'Please enter your email': 'براہ کرم اپنی ای میل درج کریں',
      'Enter a valid email': 'درست ای میل درج کریں',
      'Password': 'پاس ورڈ',
      'Please enter your password': 'براہ کرم اپنا پاس ورڈ درج کریں',
      'Password must be at least 6 characters':
          'پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے',
      'Forgot Password?': 'پاس ورڈ بھول گئے؟',
      'Confirm Password': 'پاس ورڈ کی تصدیق کریں',
      'Passwords do not match': 'پاس ورڈ مماثل نہیں ہیں',
      'Please enter your confirm password': 'براہ کرم تصدیقی پاس ورڈ درج کریں',
      'LOGIN IN': 'لاگ ان کریں',
      'Continue with Phone ': 'فون سے جاری رکھیں',
      'Do\'nt have an account? ': 'اکاؤنٹ نہیں ہے؟',
      'Register': 'رجسٹر کریں',
      'Sign Up': 'سائن اپ کریں',
      'SIGN UP': 'سائن اپ',
      'Continue with Phone': 'فون سے جاری رکھیں',
      'Continue with Gmail': 'جی میل سے جاری رکھیں',
      'Now': 'اب',
      'Magrab': 'مغرب',
      'Upcoming': 'آئندہ',
      'Asha': 'عشاء',
      '4:44 Pm': '۴:۴۴ شام',
      'Sura Al Baqra': 'سورۃ البقرہ',
      'QS:Surah Al Baqra: Ayat 30': 'قرآن: سورۃ البقرہ: آیت 30',
      'Videos': 'ویڈیوز',
      'Quran': 'قرآن',
      'Duain': 'دعائیں',
      'Names': 'اسماء',
      'Tasbeeh': 'تسبیح',
      'Quarnin Duain': 'قرآنی دعائیں',
      'Qibla': 'قبلہ',
      'Dua Before Eating': 'کھانے سے پہلے کی دعا',
      'In the name of Allah and with the blessings of Allah.':
          'اللہ کے نام سے اور اللہ کی برکتوں کے ساتھ۔',
      'Abu Dawood 3767, Ahmad': 'ابو داؤد 3767، احمد',
      'Dua After Eating': 'کھانے کے بعد کی دعا',
      'All praise is for Allah who fed me this and provided it for me without any might nor power from myself.':
          'تمام تعریفیں اللہ کے لیے ہیں جس نے مجھے یہ کھلایا اور بغیر میری طاقت اور قدرت کے مہیا فرمایا۔',
      'Abu Dawood 4023, Tirmidhi 3458': 'ابو داؤد 4023، ترمذی 3458',
      'Dua Before Sleeping': 'سونے سے پہلے کی دعا',
      'In Your name, O Allah, I die and I live.':
          'اے اللہ، تیرے نام پر میں مرتا ہوں اور جیتا ہوں۔',
      'Bukhari 6324': 'بخاری 6324',
      'Dua After Waking Up': 'جاگنے کے بعد کی دعا',
      'Praise is to Allah Who gave us life after He caused us to die, and to Him is the return.':
          'تمام تعریفیں اللہ کے لیے ہیں جس نے ہمیں موت کے بعد زندگی دی، اور اسی کی طرف لوٹنا ہے۔',
      'Bukhari 6312, Muslim 2711': 'بخاری 6312، مسلم 2711',
      'Dua When Entering the Toilet': 'ٹوائلٹ میں داخل ہونے کی دعا',
      'O Allah, I seek refuge with You from all evil and evil-doers.':
          'اے اللہ! میں تجھ سے ہر برائی اور برے کاموں سے پناہ مانگتا ہوں۔',
      'Bukhari 142, Muslim 375': 'بخاری 142، مسلم 375',
      'Dua After Leaving the Toilet': 'ٹوائلٹ سے نکلنے کی دعا',
      'I ask You for Your forgiveness.': 'میں تجھ سے بخشش مانگتا ہوں۔',
      'Abu Dawood 30, Ibn Majah 300': 'ابو داؤد 30، ابن ماجہ 300',
      'Dua When Leaving the House': 'گھر سے نکلتے وقت کی دعا',
      'In the name of Allah, I place my trust in Allah, and there is no might nor power except with Allah.':
          'اللہ کے نام کے ساتھ، میں اللہ پر بھروسہ کرتا ہوں، اور اللہ کے سوا کوئی طاقت و قوت نہیں۔',
      'Abu Dawood 5095, Tirmidhi 3426': 'ابو داؤد 5095، ترمذی 3426',
      'Dua When Entering the House': 'گھر میں داخل ہوتے وقت کی دعا',
      'O Allah, I ask You for the best of entrances and the best of exits.':
          'اے اللہ! میں تجھ سے بہترین داخلہ اور بہترین اخراج مانگتا ہوں۔',
      'Abu Dawood 5096': 'ابو داؤد 5096',
      'Dua for Traveling': 'سفر کی دعا',
      'Glory is to Him Who has made this [vehicle] subservient to us, and we ourselves could never have accomplished it. And verily, to our Lord we are returning.':
          'پاک ہے وہ ذات جس نے اس (سواری) کو ہمارے تابع بنایا، ورنہ ہم اس کو قابو میں نہیں لا سکتے تھے، اور ہم یقیناً اپنے رب کی طرف لوٹنے والے ہیں۔',
      'Dua When in Distress': 'پریشانی کے وقت کی دعا',
      'There is none worthy of worship except Allah, the Most Great, the Most Forbearing. There is none worthy of worship except Allah, the Lord of the Mighty Throne.':
          'اللہ کے سوا کوئی معبود نہیں، جو عظیم اور بردبار ہے۔ اللہ کے سوا کوئی معبود نہیں، جو عرش عظیم کا مالک ہے۔',
      'Bukhari 6345, Muslim 2730': 'بخاری 6345، مسلم 2730',
      'Translation: ': 'ترجمہ:',
      'Reference: ': 'حوالہ:',
      'Asma Ul Husna': 'اسماء الحسنیٰ',
      'Names of Allah': 'اللہ کے نام',
       'Ar-Rahmān': 'الرحمٰن',
      'Ar-Rahīm': 'الرحیم',
      'The Bestower of Mercy': 'رحمت عطا کرنے والا',
      'Al-Malik': 'الملک',
      'The King and Owner of Dominion': 'بادشاہ اور ملکیت کا مالک',
      'Al-Quddūs': 'القدوس',
      'The Absolutely Pure': 'بالکل پاک',
      'As-Salām': 'السلام',
      'The Source of Peace, Safety, and Perfection':
          'سلامتی، امن اور کمال کا ماخذ',
      'Al-Mu’min': 'المؤمن',
      'The One Who gives Emaan and Security': 'ایمان اور تحفظ دینے والا',
      'Al-Muhaymin': 'المھیمن',
      'The Guardian, The Witness, The Overseer': 'نگہبان، گواہ اور نگران',
      'Al-‘Azīz': 'العزیز',
      'The Almighty': 'زبردست',
      'Al-Jabbār': 'الجبار',
      'The Compeller, The Restorer': 'زبردستی کرنے والا، بحال کرنے والا',
      'Al-Mutakabbir': 'المتكبر',
      'The Supreme, The Majestic': 'سب سے بالا، عظیم',
      'Al-Khāliq': 'الخالق',
      'The Creator, The Maker': 'پیدا کرنے والا، بنانے والا',
      'Al-Bāriʾ': 'البارئ',
      'Al-Muṣawwir': 'المصور',
      'The Fashioner': 'صورت بنانے والا',
      'Al-Ghaffār': 'الغفار',
      'The Constant Forgiver': 'ہمیشہ معاف کرنے والا',
      'Al-Qahhār': 'القهار',
      'The All-Subduer': 'سب پر غالب',
      'Al-Wahhāb': 'الوھاب',
      'The Supreme Bestower': 'سب سے بڑا عطا کرنے والا',
      'Ar-Razzāq': 'الرزاق',
      'The Provider': 'رزق دینے والا',
      'Al-Fattāḥ': 'الفتاح',
      'The Supreme Opener': 'فیصلہ کرنے والا',
      'Al-‘Alīm': 'العلیم',
      'The All-Knowing': 'سب کچھ جاننے والا',
       'Al-Qābiḍ': 'القابض',
      'The Withholder': 'روکنے والا',
      'Al-Bāsiṭ': 'الباسط',
      'The Extender': 'کشادہ کرنے والا',
      'Al-Khāfiḍ': 'الخافض',
      'The Reducer': 'پست کرنے والا',
      'Ar-Rāfiʿ': 'الرافع',
      'The Exalter, The Elevator': 'بلند کرنے والا',
      'Al-Muʿizz': 'المعز',
      'The Honourer, the Bestower': 'عزت دینے والا',
      'Al-Mudhill': 'المذل',
      'The Dishonourer': 'ذلیل کرنے والا',
      'As-Samīʿ': 'السميع',
      'The All-Hearing': 'سب کچھ سننے والا',
      'Al-Baṣīr': 'البصير',
      'The All-Seeing': 'سب کچھ دیکھنے والا',
      'Al-Ḥakam': 'الحكم',
      'The Impartial Judge': 'انصاف کرنے والا',
      'Al-ʿAdl': 'العدل',
      'The Utterly Just': 'بہت انصاف کرنے والا',
      'Al-Laṭīf': 'اللطيف',
      'The Subtle One, The Most Gentle': 'باریک بین، نہایت مہربان',
      'Al-Khabīr': 'الخبير',
      'The Acquainted, The All-Aware': 'ہر چیز سے باخبر',
      'Al-Ḥalīm': 'الحليم',
      'The Most Forbearing': 'بردبار',
      'Al-ʿAẓīm': 'العظيم',
      'The Magnificent, The Supreme': 'نہایت عظمت والا',
      'Al-Ghafūr': 'الغفور',
      'The Forgiving, The Exceedingly Forgiving': 'بخشنے والا',
      'Ash-Shakūr': 'الشكور',
      'The Most Appreciative': 'قدردان',
      'Al-ʿAlī': 'العلى',
      'The Most High, The Exalted': 'بلند و برتر',
      'Al-Kabīr': 'الكبير',
      'The Greatest, The Most Grand': 'سب سے بڑا',
      'Al-Ḥafīẓ': 'الحفيظ',
      'The Preserver, The All-Heedful and All-Protecting':
          'محافظ، سب کا نگہبان',
      'Al-Muqīt': 'المقيت',
      'The Sustainer, The Maintainer': 'روزى دینے والا',
      'Al-Ḥasīb': 'الحسيب',
      'The Reckoner': 'حساب لینے والا',
      'Al-Jalīl': 'الجليل',
      'The Majestic': 'جلال والا',
      'Al-Karīm': 'الكريم',
      'The Most Generous, The Most Esteemed': 'نہایت کریم',
      'Ar-Raqeeb': 'الرقيب',
      'The Watchful, The All-Watchful': 'نگہبان',
      'Al-Mujeeb': 'المجيب',
      'The Responsive, The Answerer': 'دعا قبول کرنے والا',
      'Al-Waasi’': 'الواسع',
      'The All-Encompassing, the Boundless': 'وسیع علم والا',
      'Al-Hakeem': 'الحكيم',
      'The All-Wise': 'حکمت والا',
      'Al-Wadud': 'الودود',
      'The Most Loving': 'محبت کرنے والا',
      'Al-Majeed': 'المجيد',
      'The Glorious, The Most Honorable': 'عظمت اور بزرگی والا',
      'Al-Baa’ith': 'الباعث',
      'The Infuser of New Life': 'زندہ کرنے والا',
      'As-Shaheed': 'الشهيد',
      'The All Observing Witnessing': 'گواہ',
      'Al-Haqq': 'الحق',
      'The Absolute Truth': 'سچائی',
      'Al-Wakeel': 'الوكيل',
      'The Trustee, The Disposer of Affairs': 'کارساز',
      'Al-Qawiyy': 'القوي',
      'The All-Strong': 'قوت والا',
      'Al-Mateen': 'المتين',
      'The Firm, The Steadfast': 'مضبوطی والا',
      'Al-Walee': 'الولي',
      'The Protecting Associate': 'دوست اور مددگار',
      'Al-Hameed': 'الحميد',
      'The Praiseworthy': 'تعریف کے لائق',
      'Al-Muhsee': 'المحصي',
      'The All-Enumerating, The Counter': 'گننے والا',
      'Al-Mubdi’': 'المبدئ',
      'The Originator, The Initiator': 'پہلی بار پیدا کرنے والا',
      'Al-Mu’id': 'المعيد',
      'The Restorer, The Reinstater': 'دوبارہ لوٹانے والا',
      'Al-Muhyee': 'المحيي',
      'The Giver of Life': 'زندگی دینے والا',
      'Al-Mumeet': 'المميت',
      'The Creator of Death': 'موت دینے والا',
      'Al-Hayy': 'الحي',
      'The Ever-Living': 'ہمیشہ زندہ',
      'Al-Qayyoom': 'القيوم',
      'The Sustainer, The Self-Subsisting': 'قائم رکھنے والا',
      'Al-Waajid': 'الواجد',
      'The Perceiver': 'پانے والا',
      'Al-Maajid': 'الماجد',
      'The Illustrious, The Magnificent': 'عزت و شرافت والا',
      'Al-Waahid': 'الواحد',
      'The One, The Indivisible': 'ایک، ناقابل تقسیم',
      'Al-Ahad': 'الاحد',
      'The Unique, The Only One': 'منفرد، اکیلا',
      'As-Samad': 'الصمد',
      'The Eternal, Satisfier of Needs': 'بے نیاز',
      'Al-Qaadir': 'القادر',
      'The Omnipotent': 'سب پر قدرت رکھنے والا',
      'Al-Muqtadir': 'المقتدر',
      'The Powerful': 'طاقتور',
      'Al-Muqaddim': 'المقدم',
      'The Expediter, The Promoter': 'جلدی کرنے والا، آگے بڑھانے والا',
      'Al-Mu’akhkhir': 'المؤخر',
      'The Delayer': 'پیچھے رکھنے والا',
      'Al-Awwal': 'الأول',
      'The First': 'پہلا',
      'Al-Aakhir': 'الآخر',
      'The Last, The Utmost': 'آخری',
      'Az-Zaahir': 'الظاهر',
      'The Manifest, The All-Surpassing': 'ظاہر، سب پر غالب',
      'Al-Baatin': 'الباطن',
      'The Hidden One, Knower of the Hidden':
          'پوشیدہ، چھپی باتوں کا جاننے والا',
      'Al-Waalee': 'الوالي',
      'The Sole Governor': 'واحد حکمران',
      'Al-Muta’ali': 'المتعالي',
      'The Self Exalted': 'بلندی والا',
      'Al-Barr': 'البر',
      'The Source of All Goodness': 'بھلائی کا سرچشمہ',
      'At-Tawwaab': 'التواب',
      'The Ever-Pardoning': 'بار بار معاف کرنے والا',
      'Al-Muntaqim': 'المنتقم',
      'The Avenger': 'بدلہ لینے والا',
      'Al-‘Afuww': 'العفو',
      'The Pardoner': 'معاف کرنے والا',
      'Ar-Ra’ūf': 'الرؤوف',
      'The Most Kind': 'نہایت مہربان',
      'Mālik al-Mulk': 'مالك الملك',
      'Master of the Dominion,\nOwner of the Kingdom': 'بادشاہی کا مالک',
      'Thul-Jalaali wal-Ikraam': 'ذو الجلال والإكرام',
      'Possessor of Glory and Honour': 'جلال اور عزت کا مالک',
      'Al-Muqsiṭ': 'المقسط',
      'The Just One': 'انصاف کرنے والا',
      'Al-Jaami’': 'الجامع',
      'The Gatherer, the Uniter': 'اکٹھا کرنے والا',
      'Al-Ghaniyy': 'الغني',
      'The Self-Sufficient, The Wealthy': 'بے نیاز، مالدار',
      'Al-Mughniyy': 'المغني',
      'The Enricher': 'غنی بنانے والا',
      'Al-Maani’': 'المانع',
      'The With holder': 'روکنے والا',
      'Ad-Dārr': 'الضار',
      'The Distresser': 'تکلیف دینے والا',
      'An-Naafi’': 'النافع',
      'The Propitious, The Benefactor': 'فائدہ دینے والا',
      'An-Noor': 'النور',
      'The Light': 'روشنی',
      'Al-Haadi': 'الهادي',
      'The Guide': 'ہدایت دینے والا',
      'Al-Badee’': 'البديع',
      'The Incomparable Originator': 'بے مثال پیدا کرنے والا',
      'Al-Baaqi': 'الباقي',
      'The Ever-Lasting': 'ہمیشہ رہنے والا',
      'Al-Waarith': 'الوارث',
      'The Inheritor': 'وارث',
      'Ar-Rasheed': 'الرشيد',
      'The Guide to the Right Path': 'راہ راست دکھانے والا',
      'Al-Saboor': 'الصبور',
      'The Patient': 'صبر والا',
  'Juzz': 'جز',
  'Setting': 'ترتیبات',
  'Account': 'اکاؤنٹ',
  'Privacy, security, change number': 'پرائیویسی، سیکیورٹی، نمبر تبدیل کریں',
  'Notifications': 'اطلاعات',
  'Message, group & call tones': 'پیغام، گروپ اور کال ٹونز',
  'Language': 'زبان',
  'App language': 'ایپ کی زبان',
  'Theme': 'تھیم',
  'Light / Dark mode': 'روشن / تاریک موڈ',
  'About': 'ایپ کے بارے میں',
  'App version, developer info': 'ایپ ورژن، ڈیولپر کی معلومات',
  'Logout': 'لاگ آؤٹ',
  'Qaris List' :'قاریوں کی فہرست',
  'Surah List' : 'سورہ فہرست',
  "Tafseer":'تفسیر',
  "Translation":'ترجمہ'
    },
  };


}
