import 'package:flutter/material.dart';

class NamesViewModel extends ChangeNotifier {
  List<Map<dynamic, dynamic>> nameData = [
    {
      'name': 'ٱلرَّحْمَٰنُ',
      'tra': 'Ar-Rahmān',
      'meaning': 'The Most or Entirely Merciful',
    },
    {
      'name': 'ٱلرَّحِيمُ',
      'tra': 'Ar-Rahīm',
      'meaning': 'The Bestower of Mercy',
    },
    {
      'name': 'ٱلْمَلِكُ',
      'tra': 'Al-Malik',
      'meaning': 'The King and Owner of Dominion',
    },
    {
      'name': 'ٱلْقُدُّوسُ',
      'tra': 'Al-Quddūs',
      'meaning': 'The Absolutely Pure',
    },
    {
      'name': 'ٱلسَّلَامُ',
      'tra': 'As-Salām',
      'meaning': 'The Source of Peace, Safety, and Perfection',
    },
    {
      'name': 'ٱلْمُؤْمِنُ',
      'tra': 'Al-Mu’min',
      'meaning': 'The One Who gives Emaan and Security',
    },
    {
      'name': 'ٱلْمُهَيْمِنُ',
      'tra': 'Al-Muhaymin',
      'meaning': 'The Guardian, The Witness, The Overseer',
    },
    {'name': 'ٱلْعَزِيزُ', 'tra': 'Al-‘Azīz', 'meaning': 'The Almighty'},
    {
      'name': 'ٱلْجَبَّارُ',
      'tra': 'Al-Jabbār',
      'meaning': 'The Compeller, The Restorer',
    },
    {
      'name': 'ٱلْمُتَكَبِّر',
      'tra': 'Al-Mutakabbir',
      'meaning': 'The Supreme, The Majestic',
    },
    {
      'name': 'ٱلْخَالِقُ',
      'tra': 'Al-Khāliq',
      'meaning': 'The Creator, The Maker',
    },
    {'name': 'ٱلْبَارِئُ', 'tra': 'Al-Bāriʾ', 'meaning': 'The Evolver'},
    {'name': 'ٱلْمُصَوِّرُ', 'tra': 'Al-Muṣawwir', 'meaning': 'The Fashioner'},
    {
      'name': 'ٱلْغَفَّارُ',
      'tra': 'Al-Ghaffār',
      'meaning': 'The Constant Forgiver',
    },
    {'name': 'ٱلْقَهَّارُ', 'tra': 'Al-Qahhār', 'meaning': 'The All-Subduer'},
    {
      'name': 'ٱلْوَهَّابُ',
      'tra': 'Al-Wahhāb',
      'meaning': 'The Supreme Bestower',
    },
    {'name': 'ٱلرَّزَّاقُ', 'tra': 'Ar-Razzāq', 'meaning': 'The Provider'},
    {
      'name': 'ٱلْفَتَّاحُ',
      'tra': 'Al-Fattāḥ',
      'meaning': 'The Supreme Opener',
    },
    {'name': 'ٱلْعَلِيمُ', 'tra': 'Al-‘Alīm', 'meaning': 'The All-Knowing'},
    {'name': 'ٱلْقَابِضُ', 'tra': 'Al-Qābiḍ', 'meaning': 'The Withholder'},
    {'name': 'ٱلْبَاسِطُ', 'tra': 'Al-Bāsiṭ', 'meaning': 'The Extender'},
    {'name': 'ٱلْخَافِضُ', 'tra': 'Al-Khāfiḍ', 'meaning': 'The Reducer'},
    {
      'name': 'ٱلرَّافِعُ',
      'tra': 'Ar-Rāfiʿ',
      'meaning': 'The Exalter, The Elevator',
    },
    {
      'name': 'ٱلْمُعِزُّ',
      'tra': 'Al-Muʿizz',
      'meaning': 'The Honourer, the Bestower',
    },
    {'name': 'ٱلْمُذِلُّ', 'tra': 'Al-Mudhill', 'meaning': 'The Dishonourer'},
    {'name': 'ٱلسَّمِيعُ', 'tra': 'As-Samīʿ', 'meaning': 'The All-Hearing'},
    {'name': 'ٱلْبَصِيرُ', 'tra': 'Al-Baṣīr', 'meaning': 'The All-Seeing'},
    {'name': 'ٱلْحَكَمُ', 'tra': 'Al-Ḥakam', 'meaning': 'The Impartial Judge'},
    {'name': 'ٱلْعَدْلُ', 'tra': 'Al-ʿAdl', 'meaning': 'The Utterly Just'},
    {
      'name': 'ٱلْلَّطِيفُ',
      'tra': 'Al-Laṭīf',
      'meaning': 'The Subtle One, The Most Gentle',
    },
    {
      'name': 'ٱلْخَبِيرُ',
      'tra': 'Al-Khabīr',
      'meaning': 'The Acquainted, The All-Aware',
    },
    {'name': 'ٱلْحَلِيمُ', 'tra': 'Al-Ḥalīm', 'meaning': 'The Most Forbearing'},
    {
      'name': 'ٱلْعَظِيمُ',
      'tra': 'Al-ʿAẓīm',
      'meaning': 'The Magnificent, The Supreme',
    },
    {
      'name': 'ٱلْغَفُورُ',
      'tra': 'Al-Ghafūr',
      'meaning': 'The Forgiving, The Exceedingly Forgiving',
    },
    {
      'name': 'ٱلشَّكُورُ',
      'tra': 'Ash-Shakūr',
      'meaning': 'The Most Appreciative',
    },
    {
      'name': 'ٱلْعَلِيُّ',
      'tra': 'Al-ʿAlī',
      'meaning': 'The Most High, The Exalted',
    },
    {
      'name': 'ٱلْكَبِيرُ',
      'tra': 'Al-Kabīr',
      'meaning': 'The Greatest, The Most Grand',
    },
    {
      'name': 'ٱلْحَفِيظُ',
      'tra': 'Al-Ḥafīẓ',
      'meaning': 'The Preserver, The All-Heedful and All-Protecting',
    },
    {
      'name': 'ٱلْمُقِيتُ',
      'tra': 'Al-Muqīt',
      'meaning': 'The Sustainer, The Maintainer',
    },
    {'name': 'ٱلْحَسِيبُ', 'tra': 'Al-Ḥasīb', 'meaning': 'The Reckoner'},
    {'name': 'ٱلْجَلِيلُ', 'tra': 'Al-Jalīl', 'meaning': 'The Majestic'},
    {
      'name': 'ٱلْكَرِيمُ',
      'tra': 'Al-Karīm',
      'meaning': 'The Most Generous, The Most Esteemed',
    },
    {
      'name': 'ٱلْرَّقِيبُ',
      'tra': 'Ar-Raqeeb',
      'meaning': '	The Watchful, The All-Watchful',
    },
    {
      'name': 'ٱلْمُجِيبُ',
      'tra': 'Al-Mujeeb',
      'meaning': 'The Responsive, The Answerer',
    },
    {
      'name': 'ٱلْوَاسِعُ',
      'tra': 'Al-Waasi’',
      'meaning': 'The All-Encompassing, the Boundless',
    },
    {'name': 'ٱلْحَكِيمُ', 'tra': 'Al-Hakeem', 'meaning': 'The All-Wise'},
    {'name': 'ٱلْوَدُودُ', 'tra': 'Al-Wadud', 'meaning': 'The Most Loving'},
    {
      'name': 'ٱلْمَجِيدُ',
      'tra': 'Al-Majeed',
      'meaning': 'The Glorious, The Most Honorable',
    },
    {
      'name': 'ٱلْبَاعِثُ',
      'tra': 'Al-Baa’ith',
      'meaning': 'The Infuser of New Life',
    },
    {
      'name': 'ٱلْشَّهِيدُ',
      'tra': 'As-Shaheed',
      'meaning': 'The All Observing Witnessing',
    },
    {'name': 'ٱلْحَقُّ', 'tra': 'Al-Haqq', 'meaning': 'The Absolute Truth'},
    {
      'name': 'ٱلْوَكِيلُ',
      'tra': 'Al-Wakeel',
      'meaning': 'The Trustee, The Disposer of Affairs',
    },
    {'name': 'ٱلْقَوِيُّ', 'tra': 'Al-Qawiyy', 'meaning': 'The All-Strong'},
    {
      'name': 'ٱلْمَتِينُ',
      'tra': 'Al-Mateen',
      'meaning': 'The Firm, The Steadfast',
    },
    {
      'name': 'ٱلْوَلِيُ',
      'tra': 'Al-Walee',
      'meaning': 'The Protecting Associate',
    },
    {'name': 'ٱلْحَمِيدُ', 'tra': 'Al-Hameed', 'meaning': 'The Praiseworthy'},
    {
      'name': 'ٱلْمُحْصِي',
      'tra': 'Al-Muhsee',
      'meaning': 'The All-Enumerating, The Counter',
    },
    {
      'name': 'ٱلْمُبْدِئُ',
      'tra': 'Al-Mubdi’',
      'meaning': 'The Originator, The Initiator',
    },
    {
      'name': 'ٱلْمُعِيدُ',
      'tra': 'Al-Mu’id',
      'meaning': 'The Restorer, The Reinstater',
    },
    {'name': 'ٱلْمُحْيِي', 'tra': 'Al-Muhyee', 'meaning': '	The Giver of Life'},
    {
      'name': 'ٱلْمُمِيتُ',
      'tra': 'Al-Mumeet',
      'meaning': 'The Creator of Death',
    },
    {'name': 'ٱلْحَيُّ', 'tra': 'Al-Hayy', 'meaning': 'The Ever-Living'},
    {
      'name': 'ٱلْقَيُّومُ',
      'tra': 'Al-Qayyoom',
      'meaning': 'The Sustainer, The Self-Subsisting',
    },
    {'name': 'ٱلْوَاجِدُ', 'tra': 'Al-Waajid', 'meaning': 'The Perceiver'},
    {
      'name': 'ٱلْمَاجِدُ',
      'tra': 'Al-Maajid',
      'meaning': 'The Illustrious, The Magnificent',
    },
    {
      'name': 'ٱلْوَاحِدُ',
      'tra': 'Al-Waahid',
      'meaning': 'The One, The Indivisible',
    },
    {
      'name': 'ٱلْأَحَدُ',
      'tra': 'Al-Ahad',
      'meaning': 'The Unique, The Only One',
    },
    {
      'name': 'ٱلصَّمَدُ',
      'tra': 'As-Samad',
      'meaning': 'The Eternal, Satisfier of Needs',
    },
    {'name': 'ٱلْقَادِرُ', 'tra': 'Al-Qaadir', 'meaning': 'The Omnipotent'},
    {'name': 'ٱلْمُقْتَدِرُ', 'tra': 'Al-Muqtadir', 'meaning': 'The Powerful'},
    {
      'name': 'ٱلْمُقَدِّمُ',
      'tra': 'Al-Muqaddim',
      'meaning': 'The Expediter, The Promoter',
    },
    {'name': 'ٱلْمُؤَخ ِّرُ', 'tra': 'Al-Mu’akhkhir', 'meaning': '	The Delayer'},
    {'name': 'ٱلْأوَّلُ', 'tra': 'Al-Awwal', 'meaning': 'The First'},
    {'name': 'ٱلْآخِرُ', 'tra': 'Al-Aakhir', 'meaning': 'The Last, The Utmost'},
    {
      'name': 'ٱلظَّٰهِرُ',
      'tra': 'Az-Zaahir',
      'meaning': 'The Manifest, The All-Surpassing',
    },
    {
      'name': 'ٱلْبَاطِنُ',
      'tra': 'Al-Baatin',
      'meaning': 'The Hidden One, Knower of the Hidden',
    },
    {'name': 'ٱلْوَالِي', 'tra': 'Al-Waalee	', 'meaning': 'he Sole Governor'},
    {
      'name': 'ٱلْمُتَعَالِي',
      'tra': 'Al-Muta’ali',
      'meaning': 'The Self Exalted',
    },
    {
      'name': 'ٱلْبَرُّ',
      'tra': 'Al-Barr',
      'meaning': 'The Source of All Goodness',
    },
    {
      'name': 'ٱلتَّوَابُ',
      'tra': 'At-Tawwaab',
      'meaning': 'The Ever-Pardoning',
    },
    {'name': 'ٱلْمُنْتَقِمُ', 'tra': 'Al-Muntaqim', 'meaning': 'The Avenger'},
    {'name': 'ٱلْعَفُوُّ', 'tra': 'Al-‘Afuww', 'meaning': 'The Pardoner'},
    {'name': 'ٱلْرَّؤُوفُ', 'tra': 'Ar-Ra’ūf', 'meaning': 'The Most Kind'},
    {
      'name': 'مَالِكُ ٱلْمُلْكِ',
      'tra': 'Mālik al-Mulk',
      'meaning': 'Master of the Dominion,\nOwner of the Kingdom',
    },
    {
      'name': 'ذُو ٱلْجَلَالِ وَٱلْإِكْرَامِ',
      'tra': 'Thul-Jalaali wal-Ikraam',
      'meaning': 'Possessor of Glory and Honour',
    },
    {'name': 'ٱلْمُقْسِطُ', 'tra': 'Al-Muqsiṭ', 'meaning': 'The Just One'},
    {
      'name': 'ٱلْجَامِعُ',
      'tra': 'Al-Jaami’',
      'meaning': 'The Gatherer, the Uniter',
    },
    {
      'name': 'ٱلْغَنيُّ',
      'tra': 'Al-Ghaniyy',
      'meaning': 'The Self-Sufficient, The Wealthy',
    },
    {'name': 'ٱلْمُغْنِيُ', 'tra': 'Al-Mughniyy', 'meaning': 'The Enricher'},
    {'name': 'ٱلْمَانِعُ', 'tra': 'Al-Maani’', 'meaning': 'The Withholder'},
    {'name': 'ٱلضَّارُّ', 'tra': 'Ad-Dārr', 'meaning': 'The Distresser'},
    {
      'name': 'ٱلنَّافِعُ',
      'tra': 'An-Naafi’',
      'meaning': 'The Propitious, The Benefactor',
    },
    {'name': 'ٱلْنُورُ', 'tra': 'An-Noor', 'meaning': 'The Light'},
    {'name': 'ٱلْهَادِي', 'tra': 'Al-Haadi', 'meaning': 'The Guide'},
    {
      'name': 'ٱلْبَدِيعُ',
      'tra': 'Al-Badee’',
      'meaning': 'The Incomparable Originator',
    },
    {'name': 'ٱلْبَاقِي', 'tra': 'Al-Baaqi', 'meaning': 'The Ever-Lasting'},
    {'name': 'ٱلْوَارِثُ', 'tra': 'Al-Waarith', 'meaning': 'The Inheritor'},
    {
      'name': 'ٱلرَّشِيدُ',
      'tra': 'Ar-Rasheed',
      'meaning': 'The Guide to the Right Path',
    },
    {'name': 'ٱلصَّبُورُ', 'tra': 'Al-Saboor', 'meaning': 'The Patient'},
  ];
}
